# Stage 1: Build ứng dụng Nuxt.js
FROM node:20 AS build

WORKDIR /app

# Sao chép package.json và package-lock.json để cài đặt dependencies
COPY package*.json ./

# Cài đặt dependencies
RUN npm install

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Build ứng dụng Nuxt.js kieu static
RUN npm run generate

# Xoa file environment
RUN rm -rf env_config.js

# Stage 2: Dùng Nginx để serve static files
FROM nginx:alpine

# Copy toàn bộ nội dung build từ Nuxt vào thư mục Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Copy file cấu hình Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80 để Nginx có thể lắng nghe
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]